### PR TITLE
"NSP-flat" collection based on https://github.com/Lopyter/stable-soup-prompts

### PR DESCRIPTION
**Pull request by illtellyoulater**
After using https://github.com/DominikDoom/a1111-sd-webui-tagcomplete for some time for autocompleting NSP wildcards right in the webui prompt, I ended up finding way more convenient to just have all wildcards files in a single flat folder.

For this reason with this PR I'd like to propose the addition of https://github.com/Lopyter/stable-soup-prompts as a submodule in /collections/nsp-flat/.

This won't create any problems to those who still prefer to use the structured NSP collection.
What do you think?

### CODE REVIEW

**Comment by akx** [comment]
>  I ended up finding way more convenient to just have all wildcards files in a single flat folder.

Mm, can you explain why it's more convenient? I'd be interested in improving the UX around the wildcard/collection experience :)

**Comment by WASasquatch** [comment]
It'd also be cool if you could just point to a NSP pantry, and have a faster parsing experience as sequential file traversing is inherently slow. That is why I built NSP the way it is. Management should be done via a UI and front-end, as the pantry is a database.

**Comment by akx** [comment]
After #341 is merged, you can just plop https://github.com/Lopyter/stable-soup-prompts/blob/main/nsp_pantry.json in your wildcards directory 😃

**Comment by akx** [comment]
I'll close this for the aforementioned reason -- you can just put the pantry JSON file from Lopyter/stable-soup-prompts in your `wildcards/` directory and it will be "expanded" into a hierarchy. 

Cc @WASasquatch - your private pantry file should also work with this, let me know if it doesn't!

**Pull request closed without merging**
