### PR TITLE
negative_prompt and UNLINK_SEED_FROM_PROMPT

### PR DESCRIPTION
**Pull request by lilly1987**
need Compatibility for https://github.com/lilly1987/AI-WEBUI-scripts-Random

### CODE REVIEW

**Comment by adieyal** [comment]
Have you tested the negative prompts? There is only ever one negative prompt - unless I'm mistaken, Webui doesn't handle multiple negative prompts like it does positive prompts.

**Comment by lilly1987** [comment]
I want various changes even in negativity

**Comment by adieyal** [comment]
Apologies for not getting to this sooner - I have had various features on the go at once. I decided to implement your features myself since there were many changes since you created this PR and writing the code from scratch would have been easier than resolving conflicts.

I implemented negative prompts in `process_batch` which is better than in `process` since it is called for every batch. That way we can re-evaluate the negative prompt once per batch instead of once per run.

**Comment by adieyal** [comment]
Could you please create a new PR for your wildcard files separate to this one? Also, I'm not going to accept the NSFW wildcards so please exclude those.

**Comment by adieyal** [comment]
I think your PR was fine - I just prefer for each PR to deal with only one feature/bug fix. Better to have 3 separate simple PRs, to one that contains 3 features

**Pull request closed without merging**
