### PR TITLE
Rework installer and requirement checks

### LINKED ISSUE #437: Make version compatibility checking stricter
We've had a bunch of issues now and in the past where people haven't upgraded `dynamicprompts` along with sddp.

I think the UI should make it very clear if you're using an incompatible/old version of DP, e.g. by making the Dynamic Prompts accordion a screaming orange or something.

We could even (try to) offer a button to upgrade DP too (though it will probably require a restart of the WebUI to properly take).

### PR DESCRIPTION
**Pull request by akx**
This PR:
* moves requirements from `requirements.txt` to the [standard](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#dependencies-optional-dependencies) TOML `project.dependencies` list
* guts `install.py` to move everything version-specific to `sd_dynamic_prompts.version_tools`
  * We now just _always_ attempt to install the requirements from `requirements`. No good reason not to, IMO :)
* switches to using `packaging`'s utilities to check whether the currently installed `dynamicprompts` version matches our specifier; this means e.g. future [compatible] versions of dynamicprompts work without having to bump the requirement here; e.g. `~=0.25.2` is fine with any 0.25 series >= 0.25.2, `~=0.25` is fine with any 0.x >= 0.25, etc. This also allows using actual ranges, if we need to, in the requirements, e.g. `~=0.25.2,<0.30` (but hopefully it never gets to that).
* improves the messaging a bit (though the formatting maybe got worse c.f. #447); see screenshot.

## Screenshot

Screenshot 2023-05-24 at 10 50 04

---

Follows up on #447, #450
Fixes #437

### CODE REVIEW

**Comment by adieyal** [comment]
Shoot - didn't realise that you were working on this now. I just pushed some temporary changes in anticipation of your update. Feel free to revert my PR.

**Review by adieyal — APPROVED** [review]

**Comment by akx** [comment]
@adieyal No worries, rebased :)

**Comment by adieyal** [comment]
I'm getting a ModuleNotFoundError:
`ModuleNotFoundError: No module named 'tomli'`

**Comment by akx** [comment]
@adieyal ah, good catch...

**Pull request merged**
