### PR TITLE
New Wildcards compatibility

### PR DESCRIPTION
**Pull request by akx**
PR for compatibility with the new wildcard backend in adieyal/dynamicprompts#56.

### CODE REVIEW

**Comment by adieyal** [comment]
Ok - published 0.20 to pypi - feel free to update requirements.txt if you're ready to release

**Comment by akx** [comment]
@adieyal Thanks! GitHub is having a Git operations outage right now, so... after that's done with 😁 https://www.githubstatus.com/incidents/52z0j6phhnjs

**Comment by akx** [comment]
@adieyal Thanks! GitHub is having a Git operations outage right now, so... after that's done with 😁 https://www.githubstatus.com/incidents/52z0j6phhnjs

**Comment by adieyal** [comment]
Looks great. There is a small issue with the way the wildcard collection is presented on the front-end. Previously it was wrapped with the `__` which made it easy to copy and paste into your prompt. I don't think it took custom wildcard wraps into account. Do you think the presentation of the collection should be handled in the payload or in the javascript?

**Comment by akx** [comment]
> Looks great. There is a small issue with the way the wildcard collection is presented on the front-end. Previously it was wrapped with the `__` which made it easy to copy and paste into your prompt. I don't think it took custom wildcard wraps into account. Do you think the presentation of the collection should be handled in the payload or in the javascript?

Ah, I'll check that, good catch. I suppose the text field on the top right should show the wrapped expression :)

**Comment by akx** [comment]
@adieyal rebased + added a second commit to make sure the textbox shows the wrapped wildcard (with the manager's configured wrap, no less!):
Screen Shot 2023-03-28 at 11 30 29

**Pull request merged**
